# Generated by Django 2.1.1 on 2018-09-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='values',
            new_name='value',
        ),
    ]
