# Generated by Django 2.1.1 on 2018-09-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180924_0608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('-created',)},
        ),
    ]
