# Generated by Django 2.1.1 on 2018-09-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180924_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='color',
            field=models.CharField(choices=[('or', 'orange'), ('bt', 'bruschetta-tomato'), ('wm', 'watermelon'), ('bw', 'bay-wharf'), ('gr', 'green'), ('cc', 'clear-chill'), ('bg', 'bright-greek')], default='or', max_length=2),
        ),
    ]
