# Generated by Django 2.1.1 on 2018-10-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_action_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='color',
            field=models.IntegerField(choices=[(1, 'orange'), (2, 'red-orange'), (3, 'radical-red'), (4, 'gray'), (5, 'green'), (6, 'blue'), (7, 'purple')], default=1),
        ),
    ]
