# Generated by Django 2.1.2 on 2018-10-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='core.Action'),
        ),
    ]
