# Generated by Django 2.1.2 on 2018-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20181011_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='daily_value',
            field=models.PositiveIntegerField(help_text='Enter a daily goal', verbose_name='Daily Value'),
        ),
    ]
